[package]
name = "crypto-primitives"
version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true

[features]
no-entrypoint = []
idl = ["dep:codama", "dep:serde_json"]

[dependencies]
codama = { workspace = true, optional = true }
pinocchio = { workspace = true }
solana-address = { workspace = true }
pinocchio-log = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
codama = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
